"""models user,reading,tarotcard all added at mvp

Revision ID: 14efcd573a72
Revises: cd67dbb96f14
Create Date: 2024-04-11 16:56:14.716225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14efcd573a72'
down_revision = 'cd67dbb96f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(), nullable=True),
    sa.Column('about_me', sa.VARCHAR(), nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
