"""models user,reading,tarotcard all

Revision ID: 949bbac1c79b
Revises: 
Create Date: 2024-04-12 11:50:09.428723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949bbac1c79b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tarot_one_id', sa.Integer(), nullable=True),
    sa.Column('tarot_two_id', sa.Integer(), nullable=True),
    sa.Column('tarot_three_id', sa.Integer(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tarot_one_id'], ['tarot_cards.id'], ),
    sa.ForeignKeyConstraint(['tarot_three_id'], ['tarot_cards.id'], ),
    sa.ForeignKeyConstraint(['tarot_two_id'], ['tarot_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('users')
    op.drop_table('tarot_cards')
    # ### end Alembic commands ###
